version: "3.9"

services:
  sql_server:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server
    environment:
      - ACCEPT_EULA = Y
      - SA_PASSWORD = SecurePass123!
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

volumes:
  mssql_data:
